//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.17929 版自动生成。
// 
#pragma warning disable 1591

namespace Sellers.WMS.Web.cn.com.webxml.webservice {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ForexRmbRateWebServiceSoap", Namespace="http://webxml.com.cn/")]
    public partial class ForexRmbRateWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getForexRmbRateOperationCompleted;
        
        private System.Threading.SendOrPostCallback getForexRmbRateProOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ForexRmbRateWebService() {
            this.Url = global::Sellers.WMS.Web.Properties.Settings.Default.Sellers_WMS_Web_cn_com_webxml_webservice_ForexRmbRateWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getForexRmbRateCompletedEventHandler getForexRmbRateCompleted;
        
        /// <remarks/>
        public event getForexRmbRateProCompletedEventHandler getForexRmbRateProCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webxml.com.cn/getForexRmbRate", RequestNamespace="http://webxml.com.cn/", ResponseNamespace="http://webxml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getForexRmbRate() {
            object[] results = this.Invoke("getForexRmbRate", new object[0]);
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getForexRmbRateAsync() {
            this.getForexRmbRateAsync(null);
        }
        
        /// <remarks/>
        public void getForexRmbRateAsync(object userState) {
            if ((this.getForexRmbRateOperationCompleted == null)) {
                this.getForexRmbRateOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetForexRmbRateOperationCompleted);
            }
            this.InvokeAsync("getForexRmbRate", new object[0], this.getForexRmbRateOperationCompleted, userState);
        }
        
        private void OngetForexRmbRateOperationCompleted(object arg) {
            if ((this.getForexRmbRateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getForexRmbRateCompleted(this, new getForexRmbRateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webxml.com.cn/getForexRmbRatePro", RequestNamespace="http://webxml.com.cn/", ResponseNamespace="http://webxml.com.cn/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet getForexRmbRatePro(string theUserID) {
            object[] results = this.Invoke("getForexRmbRatePro", new object[] {
                        theUserID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void getForexRmbRateProAsync(string theUserID) {
            this.getForexRmbRateProAsync(theUserID, null);
        }
        
        /// <remarks/>
        public void getForexRmbRateProAsync(string theUserID, object userState) {
            if ((this.getForexRmbRateProOperationCompleted == null)) {
                this.getForexRmbRateProOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetForexRmbRateProOperationCompleted);
            }
            this.InvokeAsync("getForexRmbRatePro", new object[] {
                        theUserID}, this.getForexRmbRateProOperationCompleted, userState);
        }
        
        private void OngetForexRmbRateProOperationCompleted(object arg) {
            if ((this.getForexRmbRateProCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getForexRmbRateProCompleted(this, new getForexRmbRateProCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getForexRmbRateCompletedEventHandler(object sender, getForexRmbRateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getForexRmbRateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getForexRmbRateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getForexRmbRateProCompletedEventHandler(object sender, getForexRmbRateProCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getForexRmbRateProCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getForexRmbRateProCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591